apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-1
  namespace: argocd
spec: 
  destination: 
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: server-proj-private
  source: 
    path: cluster-setups/digital-ocean/kustomization.yaml
    repoURL: git@github.com:1mbili/K8s-inzynierka.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true